/*
 * File: 103-fibonacci.c
 * Auth: Lalo Rdz
 */
#include <stdio.h>

/**
 * main - Even Liber Abbaci
 *
 * Description: Each term in Fibonacci is generated by adding the previous two
 * terms. Considering Fibonacci sequence whose values do not exceed 4,000,000
 * write a program that finds and prints the sum of the even-valued terms.
 * Return: Always 0 (Success)
 */
int main(void)
{
	long int a, b, aux;

	a = 1;
	b = 2;
	printf("%ld", b);
	while (b <= 4000000)
	{
		aux = b;
		b = a + b;
		a = aux;
		if (b % 2 == 0)
			printf(", %ld", b);
	}
	printf("\n");
	return (0);
}
