/*
 * File: 103-fibonacci.c
 * Auth: Lalo Rdz
 */
#include <stdio.h>

/**
 * main - Even Liber Abbaci
 *
 * Description: Each term in Fibonacci is generated by adding the previous two
 * terms. Considering Fibonacci sequence whose values do not exceed 4,000,000
 * write a program that finds and prints the sum of the even-valued terms.
 * Return: Always 0 (Success)
 */
int main(void)
{
	long int a, b, c, d, s;

	a = 1;
	b = 2;
	c = 3;
	s = 2;
	for (d = 2; d <= 32; d++)
	{
		if (c % 2 == 0)
			s = s + c;
		a = b;
		b = c;
		c = a + b;
	}
	printf("%ld\n", s);
	return (0);
}
